spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_lab5?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Tu100den10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true